### ISSUE TITLE
error in page 24

### ISSUE THREAD

**Issue by ZhouleiJoeStone** [lbm-principles-practice/errata#2]
in Page 24 . Thus, the **second** moment of the Boltzmann equation becomes the Cauchy
momentum equation previously seen in(1.11)

I think it should be:
Thus, the **first** moment of the Boltzmann equation becomes the Cauchy
momentum equation previously seen in(1.11)

**Comment by erlendviggen** [comment]
You are absolutely right; I made a mistake in the text there. I will add this to the errata document, and I will credit you by name, if you tell me what your name is.

**Comment by ZhouleiJoeStone** [comment]
My name is Lei Zhou.

**Comment by erlendviggen** [comment]
The errata document has now been updated with the mistake that you reported. Thank you very much!
