### ISSUE TITLE
Error page 20 (1.44b)

### ISSUE THREAD

**Issue by Alexsaphir** [lbm-principles-practice/errata#3]
I think there is an issue in the equation (1.44b) p.20, it should be the sum of the logarithm of f^{eq}_{1D} not f^{eq}.

**Comment by erlendviggen** [comment]
You're right, thanks! We'll add that to the errata document.

**Comment by Alexsaphir** [comment]
And maybe an another typo in the third equation of (1.52) p.23, where \delta_{\alpha\beta} is missing.

**Comment by erlendviggen** [comment]
I think that equation is actually as it should be. On the left-hand side of the third equation, we have the indices \alpha, \alpha, and \beta in the same term. This means that we sum over all possible values of \alpha, and that \beta is the only free index. Hence, on the right-hand side, we only have only \beta as a free index.

**Comment by Alexsaphir** [comment]
Oh sorry, you're right, I'm not used to this notation.

**Comment by erlendviggen** [comment]
The new version of the erratum is now up with your comment included. Thanks again!
